spring:
  application:
    name: gateway-server
    
zuul:
  routes:
    users: 
      path: /users/**
      serviceId: user-service
      strip-prefix: false
    accounts:
      path: /checkin/**
      serviceId: checkin-service
      strip-prefix: false  
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
  
ribbon:
  eureka:
    enabled: true
  
server:
  port: 8765